package com.sybinal.shop.mapper;

import com.sybinal.shop.model.Contect;
import com.sybinal.shop.model.ContectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contect
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int countByExample(ContectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contect
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int deleteByExample(ContectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contect
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contect
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int insert(Contect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contect
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int insertSelective(Contect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contect
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    List<Contect> selectByExample(ContectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contect
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    Contect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contect
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int updateByExampleSelective(@Param("record") Contect record, @Param("example") ContectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contect
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int updateByExample(@Param("record") Contect record, @Param("example") ContectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contect
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int updateByPrimaryKeySelective(Contect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contect
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int updateByPrimaryKey(Contect record);
}