package com.sybinal.shop.mapper;

import com.sybinal.shop.model.Ewallet;
import com.sybinal.shop.model.EwalletExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EwalletMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ewallet
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int countByExample(EwalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ewallet
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int deleteByExample(EwalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ewallet
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ewallet
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int insert(Ewallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ewallet
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int insertSelective(Ewallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ewallet
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    List<Ewallet> selectByExample(EwalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ewallet
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    Ewallet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ewallet
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int updateByExampleSelective(@Param("record") Ewallet record, @Param("example") EwalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ewallet
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int updateByExample(@Param("record") Ewallet record, @Param("example") EwalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ewallet
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int updateByPrimaryKeySelective(Ewallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ewallet
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int updateByPrimaryKey(Ewallet record);
}