package com.sybinal.shop.mapper;

import com.sybinal.shop.model.Footprint;
import com.sybinal.shop.model.FootprintExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FootprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int countByExample(FootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int deleteByExample(FootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int insert(Footprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int insertSelective(Footprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    List<Footprint> selectByExample(FootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    Footprint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByExampleSelective(@Param("record") Footprint record, @Param("example") FootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByExample(@Param("record") Footprint record, @Param("example") FootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByPrimaryKeySelective(Footprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByPrimaryKey(Footprint record);
}