package com.sybinal.shop.mapper;

import com.sybinal.shop.model.OptionValue;
import com.sybinal.shop.model.OptionValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OptionValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table option_value
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int countByExample(OptionValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table option_value
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int deleteByExample(OptionValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table option_value
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table option_value
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int insert(OptionValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table option_value
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int insertSelective(OptionValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table option_value
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    List<OptionValue> selectByExample(OptionValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table option_value
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    OptionValue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table option_value
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int updateByExampleSelective(@Param("record") OptionValue record, @Param("example") OptionValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table option_value
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int updateByExample(@Param("record") OptionValue record, @Param("example") OptionValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table option_value
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int updateByPrimaryKeySelective(OptionValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table option_value
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int updateByPrimaryKey(OptionValue record);
}