package com.sybinal.shop.mapper;

import com.sybinal.shop.model.OrderOption;
import com.sybinal.shop.model.OrderOptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int countByExample(OrderOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int deleteByExample(OrderOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int insert(OrderOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int insertSelective(OrderOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    List<OrderOption> selectByExample(OrderOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    OrderOption selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int updateByExampleSelective(@Param("record") OrderOption record, @Param("example") OrderOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int updateByExample(@Param("record") OrderOption record, @Param("example") OrderOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int updateByPrimaryKeySelective(OrderOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int updateByPrimaryKey(OrderOption record);
}