package com.sybinal.shop.mapper;

import com.sybinal.shop.model.Productimage;
import com.sybinal.shop.model.ProductimageExample;
import com.sybinal.shop.model.ProductimageWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductimageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int countByExample(ProductimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int deleteByExample(ProductimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int insert(ProductimageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int insertSelective(ProductimageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    List<ProductimageWithBLOBs> selectByExampleWithBLOBs(ProductimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    List<Productimage> selectByExample(ProductimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    ProductimageWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByExampleSelective(@Param("record") ProductimageWithBLOBs record, @Param("example") ProductimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") ProductimageWithBLOBs record, @Param("example") ProductimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByExample(@Param("record") Productimage record, @Param("example") ProductimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByPrimaryKeySelective(ProductimageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(ProductimageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByPrimaryKey(Productimage record);
}