package com.sybinal.shop.mapper;

import com.sybinal.shop.model.Productcategory;
import com.sybinal.shop.model.ProductcategoryExample;
import com.sybinal.shop.model.ProductcategoryWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductcategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int countByExample(ProductcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int deleteByExample(ProductcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int insert(ProductcategoryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int insertSelective(ProductcategoryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    List<ProductcategoryWithBLOBs> selectByExampleWithBLOBs(ProductcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    List<Productcategory> selectByExample(ProductcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    ProductcategoryWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByExampleSelective(@Param("record") ProductcategoryWithBLOBs record, @Param("example") ProductcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") ProductcategoryWithBLOBs record, @Param("example") ProductcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByExample(@Param("record") Productcategory record, @Param("example") ProductcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByPrimaryKeySelective(ProductcategoryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(ProductcategoryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByPrimaryKey(Productcategory record);
}