package com.sybinal.shop.mapper;

import com.sybinal.shop.model.UserRoles;
import com.sybinal.shop.model.UserRolesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int countByExample(UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int deleteByExample(UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int deleteByPrimaryKey(Integer userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int insert(UserRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int insertSelective(UserRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    List<UserRoles> selectByExample(UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    UserRoles selectByPrimaryKey(Integer userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int updateByExampleSelective(@Param("record") UserRoles record, @Param("example") UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int updateByExample(@Param("record") UserRoles record, @Param("example") UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int updateByPrimaryKeySelective(UserRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int updateByPrimaryKey(UserRoles record);
}