package com.sybinal.shop.mapper;

import com.sybinal.shop.model.Userroles;
import com.sybinal.shop.model.UserrolesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserrolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userroles
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int countByExample(UserrolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userroles
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int deleteByExample(UserrolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userroles
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int deleteByPrimaryKey(Integer userroleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userroles
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int insert(Userroles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userroles
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int insertSelective(Userroles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userroles
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    List<Userroles> selectByExampleWithBLOBs(UserrolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userroles
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    List<Userroles> selectByExample(UserrolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userroles
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    Userroles selectByPrimaryKey(Integer userroleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userroles
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByExampleSelective(@Param("record") Userroles record, @Param("example") UserrolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userroles
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") Userroles record, @Param("example") UserrolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userroles
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByExample(@Param("record") Userroles record, @Param("example") UserrolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userroles
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByPrimaryKeySelective(Userroles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userroles
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(Userroles record);
}