package com.sybinal.shop.mapper;

import com.sybinal.shop.model.Users;
import com.sybinal.shop.model.UsersExample;
import com.sybinal.shop.model.UsersWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int countByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int deleteByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int insert(UsersWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int insertSelective(UsersWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    List<UsersWithBLOBs> selectByExampleWithBLOBs(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    List<Users> selectByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    UsersWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByExampleSelective(@Param("record") UsersWithBLOBs record, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") UsersWithBLOBs record, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByExample(@Param("record") Users record, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByPrimaryKeySelective(UsersWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(UsersWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    int updateByPrimaryKey(Users record);
}