package com.sybinal.shop.mapper;

import com.sybinal.shop.model.Wishlist;
import com.sybinal.shop.model.WishlistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WishlistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int countByExample(WishlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int deleteByExample(WishlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int insert(Wishlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int insertSelective(Wishlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    List<Wishlist> selectByExample(WishlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    Wishlist selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int updateByExampleSelective(@Param("record") Wishlist record, @Param("example") WishlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int updateByExample(@Param("record") Wishlist record, @Param("example") WishlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int updateByPrimaryKeySelective(Wishlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    int updateByPrimaryKey(Wishlist record);
}