package com.sybinal.shop.model;

import java.util.Date;

public class ArticleCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_category.category_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_category.category_name
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_category.update_user_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_category.update_time
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_category.category_id
     *
     * @return the value of article_category.category_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_category.category_id
     *
     * @param categoryId the value for article_category.category_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_category.category_name
     *
     * @return the value of article_category.category_name
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_category.category_name
     *
     * @param categoryName the value for article_category.category_name
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_category.update_user_id
     *
     * @return the value of article_category.update_user_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_category.update_user_id
     *
     * @param updateUserId the value for article_category.update_user_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_category.update_time
     *
     * @return the value of article_category.update_time
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_category.update_time
     *
     * @param updateTime the value for article_category.update_time
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}