package com.sybinal.shop.model;

import java.util.Date;

public class Comments {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.user_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.product_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.audit
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer audit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.stars
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer stars;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.create_time
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.content
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.id
     *
     * @return the value of comments.id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.id
     *
     * @param id the value for comments.id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.user_id
     *
     * @return the value of comments.user_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.user_id
     *
     * @param userId the value for comments.user_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.product_id
     *
     * @return the value of comments.product_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.product_id
     *
     * @param productId the value for comments.product_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.audit
     *
     * @return the value of comments.audit
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getAudit() {
        return audit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.audit
     *
     * @param audit the value for comments.audit
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setAudit(Integer audit) {
        this.audit = audit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.stars
     *
     * @return the value of comments.stars
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getStars() {
        return stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.stars
     *
     * @param stars the value for comments.stars
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setStars(Integer stars) {
        this.stars = stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.create_time
     *
     * @return the value of comments.create_time
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.create_time
     *
     * @param createTime the value for comments.create_time
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.content
     *
     * @return the value of comments.content
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.content
     *
     * @param content the value for comments.content
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setContent(String content) {
        this.content = content;
    }
}