package com.sybinal.shop.model;

import java.util.Date;

public class Footprint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column footprint.id
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column footprint.userid
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column footprint.productid
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Integer productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column footprint.datetimes
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Date datetimes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column footprint.id
     *
     * @return the value of footprint.id
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column footprint.id
     *
     * @param id the value for footprint.id
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column footprint.userid
     *
     * @return the value of footprint.userid
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column footprint.userid
     *
     * @param userid the value for footprint.userid
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column footprint.productid
     *
     * @return the value of footprint.productid
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column footprint.productid
     *
     * @param productid the value for footprint.productid
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column footprint.datetimes
     *
     * @return the value of footprint.datetimes
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Date getDatetimes() {
        return datetimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column footprint.datetimes
     *
     * @param datetimes the value for footprint.datetimes
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setDatetimes(Date datetimes) {
        this.datetimes = datetimes;
    }
}