package com.sybinal.shop.model;

import java.util.Date;

public class Logistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics.id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics.company_name
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics.logistics_num
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String logisticsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics.order_num
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics.state
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics.contact_name
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String contactName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics.contact_mobile
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String contactMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics.contact_address
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String contactAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics.create_time
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics.id
     *
     * @return the value of logistics.id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics.id
     *
     * @param id the value for logistics.id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics.company_name
     *
     * @return the value of logistics.company_name
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics.company_name
     *
     * @param companyName the value for logistics.company_name
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics.logistics_num
     *
     * @return the value of logistics.logistics_num
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getLogisticsNum() {
        return logisticsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics.logistics_num
     *
     * @param logisticsNum the value for logistics.logistics_num
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setLogisticsNum(String logisticsNum) {
        this.logisticsNum = logisticsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics.order_num
     *
     * @return the value of logistics.order_num
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics.order_num
     *
     * @param orderNum the value for logistics.order_num
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics.state
     *
     * @return the value of logistics.state
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics.state
     *
     * @param state the value for logistics.state
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics.contact_name
     *
     * @return the value of logistics.contact_name
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics.contact_name
     *
     * @param contactName the value for logistics.contact_name
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics.contact_mobile
     *
     * @return the value of logistics.contact_mobile
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getContactMobile() {
        return contactMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics.contact_mobile
     *
     * @param contactMobile the value for logistics.contact_mobile
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setContactMobile(String contactMobile) {
        this.contactMobile = contactMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics.contact_address
     *
     * @return the value of logistics.contact_address
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getContactAddress() {
        return contactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics.contact_address
     *
     * @param contactAddress the value for logistics.contact_address
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setContactAddress(String contactAddress) {
        this.contactAddress = contactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics.create_time
     *
     * @return the value of logistics.create_time
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics.create_time
     *
     * @param createTime the value for logistics.create_time
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}