package com.sybinal.shop.model;

import java.util.ArrayList;
import java.util.List;

public class OrderOptionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public OrderOptionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdIsNull() {
            addCriterion("order_Item_Id is null");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdIsNotNull() {
            addCriterion("order_Item_Id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdEqualTo(String value) {
            addCriterion("order_Item_Id =", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdNotEqualTo(String value) {
            addCriterion("order_Item_Id <>", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdGreaterThan(String value) {
            addCriterion("order_Item_Id >", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_Item_Id >=", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdLessThan(String value) {
            addCriterion("order_Item_Id <", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdLessThanOrEqualTo(String value) {
            addCriterion("order_Item_Id <=", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdLike(String value) {
            addCriterion("order_Item_Id like", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdNotLike(String value) {
            addCriterion("order_Item_Id not like", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdIn(List<String> values) {
            addCriterion("order_Item_Id in", values, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdNotIn(List<String> values) {
            addCriterion("order_Item_Id not in", values, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdBetween(String value1, String value2) {
            addCriterion("order_Item_Id between", value1, value2, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdNotBetween(String value1, String value2) {
            addCriterion("order_Item_Id not between", value1, value2, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOptionIdIsNull() {
            addCriterion("option_id is null");
            return (Criteria) this;
        }

        public Criteria andOptionIdIsNotNull() {
            addCriterion("option_id is not null");
            return (Criteria) this;
        }

        public Criteria andOptionIdEqualTo(Integer value) {
            addCriterion("option_id =", value, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdNotEqualTo(Integer value) {
            addCriterion("option_id <>", value, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdGreaterThan(Integer value) {
            addCriterion("option_id >", value, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("option_id >=", value, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdLessThan(Integer value) {
            addCriterion("option_id <", value, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdLessThanOrEqualTo(Integer value) {
            addCriterion("option_id <=", value, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdIn(List<Integer> values) {
            addCriterion("option_id in", values, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdNotIn(List<Integer> values) {
            addCriterion("option_id not in", values, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdBetween(Integer value1, Integer value2) {
            addCriterion("option_id between", value1, value2, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("option_id not between", value1, value2, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionValueIdIsNull() {
            addCriterion("option_value_id is null");
            return (Criteria) this;
        }

        public Criteria andOptionValueIdIsNotNull() {
            addCriterion("option_value_id is not null");
            return (Criteria) this;
        }

        public Criteria andOptionValueIdEqualTo(Integer value) {
            addCriterion("option_value_id =", value, "optionValueId");
            return (Criteria) this;
        }

        public Criteria andOptionValueIdNotEqualTo(Integer value) {
            addCriterion("option_value_id <>", value, "optionValueId");
            return (Criteria) this;
        }

        public Criteria andOptionValueIdGreaterThan(Integer value) {
            addCriterion("option_value_id >", value, "optionValueId");
            return (Criteria) this;
        }

        public Criteria andOptionValueIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("option_value_id >=", value, "optionValueId");
            return (Criteria) this;
        }

        public Criteria andOptionValueIdLessThan(Integer value) {
            addCriterion("option_value_id <", value, "optionValueId");
            return (Criteria) this;
        }

        public Criteria andOptionValueIdLessThanOrEqualTo(Integer value) {
            addCriterion("option_value_id <=", value, "optionValueId");
            return (Criteria) this;
        }

        public Criteria andOptionValueIdIn(List<Integer> values) {
            addCriterion("option_value_id in", values, "optionValueId");
            return (Criteria) this;
        }

        public Criteria andOptionValueIdNotIn(List<Integer> values) {
            addCriterion("option_value_id not in", values, "optionValueId");
            return (Criteria) this;
        }

        public Criteria andOptionValueIdBetween(Integer value1, Integer value2) {
            addCriterion("option_value_id between", value1, value2, "optionValueId");
            return (Criteria) this;
        }

        public Criteria andOptionValueIdNotBetween(Integer value1, Integer value2) {
            addCriterion("option_value_id not between", value1, value2, "optionValueId");
            return (Criteria) this;
        }

        public Criteria andOptionValueNameIsNull() {
            addCriterion("option_value_name is null");
            return (Criteria) this;
        }

        public Criteria andOptionValueNameIsNotNull() {
            addCriterion("option_value_name is not null");
            return (Criteria) this;
        }

        public Criteria andOptionValueNameEqualTo(String value) {
            addCriterion("option_value_name =", value, "optionValueName");
            return (Criteria) this;
        }

        public Criteria andOptionValueNameNotEqualTo(String value) {
            addCriterion("option_value_name <>", value, "optionValueName");
            return (Criteria) this;
        }

        public Criteria andOptionValueNameGreaterThan(String value) {
            addCriterion("option_value_name >", value, "optionValueName");
            return (Criteria) this;
        }

        public Criteria andOptionValueNameGreaterThanOrEqualTo(String value) {
            addCriterion("option_value_name >=", value, "optionValueName");
            return (Criteria) this;
        }

        public Criteria andOptionValueNameLessThan(String value) {
            addCriterion("option_value_name <", value, "optionValueName");
            return (Criteria) this;
        }

        public Criteria andOptionValueNameLessThanOrEqualTo(String value) {
            addCriterion("option_value_name <=", value, "optionValueName");
            return (Criteria) this;
        }

        public Criteria andOptionValueNameLike(String value) {
            addCriterion("option_value_name like", value, "optionValueName");
            return (Criteria) this;
        }

        public Criteria andOptionValueNameNotLike(String value) {
            addCriterion("option_value_name not like", value, "optionValueName");
            return (Criteria) this;
        }

        public Criteria andOptionValueNameIn(List<String> values) {
            addCriterion("option_value_name in", values, "optionValueName");
            return (Criteria) this;
        }

        public Criteria andOptionValueNameNotIn(List<String> values) {
            addCriterion("option_value_name not in", values, "optionValueName");
            return (Criteria) this;
        }

        public Criteria andOptionValueNameBetween(String value1, String value2) {
            addCriterion("option_value_name between", value1, value2, "optionValueName");
            return (Criteria) this;
        }

        public Criteria andOptionValueNameNotBetween(String value1, String value2) {
            addCriterion("option_value_name not between", value1, value2, "optionValueName");
            return (Criteria) this;
        }

        public Criteria andOptionNameIsNull() {
            addCriterion("option_name is null");
            return (Criteria) this;
        }

        public Criteria andOptionNameIsNotNull() {
            addCriterion("option_name is not null");
            return (Criteria) this;
        }

        public Criteria andOptionNameEqualTo(String value) {
            addCriterion("option_name =", value, "optionName");
            return (Criteria) this;
        }

        public Criteria andOptionNameNotEqualTo(String value) {
            addCriterion("option_name <>", value, "optionName");
            return (Criteria) this;
        }

        public Criteria andOptionNameGreaterThan(String value) {
            addCriterion("option_name >", value, "optionName");
            return (Criteria) this;
        }

        public Criteria andOptionNameGreaterThanOrEqualTo(String value) {
            addCriterion("option_name >=", value, "optionName");
            return (Criteria) this;
        }

        public Criteria andOptionNameLessThan(String value) {
            addCriterion("option_name <", value, "optionName");
            return (Criteria) this;
        }

        public Criteria andOptionNameLessThanOrEqualTo(String value) {
            addCriterion("option_name <=", value, "optionName");
            return (Criteria) this;
        }

        public Criteria andOptionNameLike(String value) {
            addCriterion("option_name like", value, "optionName");
            return (Criteria) this;
        }

        public Criteria andOptionNameNotLike(String value) {
            addCriterion("option_name not like", value, "optionName");
            return (Criteria) this;
        }

        public Criteria andOptionNameIn(List<String> values) {
            addCriterion("option_name in", values, "optionName");
            return (Criteria) this;
        }

        public Criteria andOptionNameNotIn(List<String> values) {
            addCriterion("option_name not in", values, "optionName");
            return (Criteria) this;
        }

        public Criteria andOptionNameBetween(String value1, String value2) {
            addCriterion("option_name between", value1, value2, "optionName");
            return (Criteria) this;
        }

        public Criteria andOptionNameNotBetween(String value1, String value2) {
            addCriterion("option_name not between", value1, value2, "optionName");
            return (Criteria) this;
        }

        public Criteria andOptionValueKeyIsNull() {
            addCriterion("option_value_key is null");
            return (Criteria) this;
        }

        public Criteria andOptionValueKeyIsNotNull() {
            addCriterion("option_value_key is not null");
            return (Criteria) this;
        }

        public Criteria andOptionValueKeyEqualTo(String value) {
            addCriterion("option_value_key =", value, "optionValueKey");
            return (Criteria) this;
        }

        public Criteria andOptionValueKeyNotEqualTo(String value) {
            addCriterion("option_value_key <>", value, "optionValueKey");
            return (Criteria) this;
        }

        public Criteria andOptionValueKeyGreaterThan(String value) {
            addCriterion("option_value_key >", value, "optionValueKey");
            return (Criteria) this;
        }

        public Criteria andOptionValueKeyGreaterThanOrEqualTo(String value) {
            addCriterion("option_value_key >=", value, "optionValueKey");
            return (Criteria) this;
        }

        public Criteria andOptionValueKeyLessThan(String value) {
            addCriterion("option_value_key <", value, "optionValueKey");
            return (Criteria) this;
        }

        public Criteria andOptionValueKeyLessThanOrEqualTo(String value) {
            addCriterion("option_value_key <=", value, "optionValueKey");
            return (Criteria) this;
        }

        public Criteria andOptionValueKeyLike(String value) {
            addCriterion("option_value_key like", value, "optionValueKey");
            return (Criteria) this;
        }

        public Criteria andOptionValueKeyNotLike(String value) {
            addCriterion("option_value_key not like", value, "optionValueKey");
            return (Criteria) this;
        }

        public Criteria andOptionValueKeyIn(List<String> values) {
            addCriterion("option_value_key in", values, "optionValueKey");
            return (Criteria) this;
        }

        public Criteria andOptionValueKeyNotIn(List<String> values) {
            addCriterion("option_value_key not in", values, "optionValueKey");
            return (Criteria) this;
        }

        public Criteria andOptionValueKeyBetween(String value1, String value2) {
            addCriterion("option_value_key between", value1, value2, "optionValueKey");
            return (Criteria) this;
        }

        public Criteria andOptionValueKeyNotBetween(String value1, String value2) {
            addCriterion("option_value_key not between", value1, value2, "optionValueKey");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_option
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 14 21:24:32 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_option
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}