package com.sybinal.shop.model;

public class OrderOption {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_option.id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_option.order_Item_Id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String orderItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_option.option_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer optionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_option.option_value_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer optionValueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_option.option_value_name
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String optionValueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_option.option_name
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String optionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_option.option_value_key
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String optionValueKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_option.id
     *
     * @return the value of order_option.id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_option.id
     *
     * @param id the value for order_option.id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_option.order_Item_Id
     *
     * @return the value of order_option.order_Item_Id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getOrderItemId() {
        return orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_option.order_Item_Id
     *
     * @param orderItemId the value for order_option.order_Item_Id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setOrderItemId(String orderItemId) {
        this.orderItemId = orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_option.option_id
     *
     * @return the value of order_option.option_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getOptionId() {
        return optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_option.option_id
     *
     * @param optionId the value for order_option.option_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setOptionId(Integer optionId) {
        this.optionId = optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_option.option_value_id
     *
     * @return the value of order_option.option_value_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getOptionValueId() {
        return optionValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_option.option_value_id
     *
     * @param optionValueId the value for order_option.option_value_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setOptionValueId(Integer optionValueId) {
        this.optionValueId = optionValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_option.option_value_name
     *
     * @return the value of order_option.option_value_name
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getOptionValueName() {
        return optionValueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_option.option_value_name
     *
     * @param optionValueName the value for order_option.option_value_name
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setOptionValueName(String optionValueName) {
        this.optionValueName = optionValueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_option.option_name
     *
     * @return the value of order_option.option_name
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getOptionName() {
        return optionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_option.option_name
     *
     * @param optionName the value for order_option.option_name
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setOptionName(String optionName) {
        this.optionName = optionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_option.option_value_key
     *
     * @return the value of order_option.option_value_key
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getOptionValueKey() {
        return optionValueKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_option.option_value_key
     *
     * @param optionValueKey the value for order_option.option_value_key
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setOptionValueKey(String optionValueKey) {
        this.optionValueKey = optionValueKey;
    }
}