package com.sybinal.shop.model;

import java.util.Date;

public class OrderHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_history.id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_history.order_num
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_history.status
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_history.note
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_history.update_user_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_history.create_time
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_history.id
     *
     * @return the value of order_history.id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_history.id
     *
     * @param id the value for order_history.id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_history.order_num
     *
     * @return the value of order_history.order_num
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_history.order_num
     *
     * @param orderNum the value for order_history.order_num
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_history.status
     *
     * @return the value of order_history.status
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_history.status
     *
     * @param status the value for order_history.status
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_history.note
     *
     * @return the value of order_history.note
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_history.note
     *
     * @param note the value for order_history.note
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_history.update_user_id
     *
     * @return the value of order_history.update_user_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_history.update_user_id
     *
     * @param updateUserId the value for order_history.update_user_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_history.create_time
     *
     * @return the value of order_history.create_time
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_history.create_time
     *
     * @param createTime the value for order_history.create_time
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}