package com.sybinal.shop.model;

import java.util.Date;

public class OrderInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_num
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.price
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.payment_flag
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer paymentFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.user_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.contact_name
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String contactName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.contact_mobile
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String contactMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.contact_address
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String contactAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.message
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.status
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.type
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.create_time
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_num
     *
     * @return the value of order_info.order_num
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_num
     *
     * @param orderNum the value for order_info.order_num
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.price
     *
     * @return the value of order_info.price
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.price
     *
     * @param price the value for order_info.price
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setPrice(String price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.payment_flag
     *
     * @return the value of order_info.payment_flag
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getPaymentFlag() {
        return paymentFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.payment_flag
     *
     * @param paymentFlag the value for order_info.payment_flag
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setPaymentFlag(Integer paymentFlag) {
        this.paymentFlag = paymentFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.user_id
     *
     * @return the value of order_info.user_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.user_id
     *
     * @param userId the value for order_info.user_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.contact_name
     *
     * @return the value of order_info.contact_name
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.contact_name
     *
     * @param contactName the value for order_info.contact_name
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.contact_mobile
     *
     * @return the value of order_info.contact_mobile
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getContactMobile() {
        return contactMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.contact_mobile
     *
     * @param contactMobile the value for order_info.contact_mobile
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setContactMobile(String contactMobile) {
        this.contactMobile = contactMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.contact_address
     *
     * @return the value of order_info.contact_address
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getContactAddress() {
        return contactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.contact_address
     *
     * @param contactAddress the value for order_info.contact_address
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setContactAddress(String contactAddress) {
        this.contactAddress = contactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.message
     *
     * @return the value of order_info.message
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.message
     *
     * @param message the value for order_info.message
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.status
     *
     * @return the value of order_info.status
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.status
     *
     * @param status the value for order_info.status
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.type
     *
     * @return the value of order_info.type
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.type
     *
     * @param type the value for order_info.type
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.create_time
     *
     * @return the value of order_info.create_time
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.create_time
     *
     * @param createTime the value for order_info.create_time
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}