package com.sybinal.shop.model;

public class OrderItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.order_num
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.product_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.price
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.quantity
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.user_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.sku_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.option_value_key_group
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String optionValueKeyGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.json_data
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String jsonData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.id
     *
     * @return the value of order_item.id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.id
     *
     * @param id the value for order_item.id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.order_num
     *
     * @return the value of order_item.order_num
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.order_num
     *
     * @param orderNum the value for order_item.order_num
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_id
     *
     * @return the value of order_item.product_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_id
     *
     * @param productId the value for order_item.product_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.price
     *
     * @return the value of order_item.price
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.price
     *
     * @param price the value for order_item.price
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.quantity
     *
     * @return the value of order_item.quantity
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.quantity
     *
     * @param quantity the value for order_item.quantity
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.user_id
     *
     * @return the value of order_item.user_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.user_id
     *
     * @param userId the value for order_item.user_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.sku_id
     *
     * @return the value of order_item.sku_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.sku_id
     *
     * @param skuId the value for order_item.sku_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.option_value_key_group
     *
     * @return the value of order_item.option_value_key_group
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getOptionValueKeyGroup() {
        return optionValueKeyGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.option_value_key_group
     *
     * @param optionValueKeyGroup the value for order_item.option_value_key_group
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setOptionValueKeyGroup(String optionValueKeyGroup) {
        this.optionValueKeyGroup = optionValueKeyGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.json_data
     *
     * @return the value of order_item.json_data
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getJsonData() {
        return jsonData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.json_data
     *
     * @param jsonData the value for order_item.json_data
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setJsonData(String jsonData) {
        this.jsonData = jsonData;
    }
}