package com.sybinal.shop.model;

import java.util.Date;

public class PaymentHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_history.id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_history.order_num
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_history.product_price
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_history.payment_type
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer paymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_history.user_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_history.payment_time
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Date paymentTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_history.id
     *
     * @return the value of payment_history.id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_history.id
     *
     * @param id the value for payment_history.id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_history.order_num
     *
     * @return the value of payment_history.order_num
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_history.order_num
     *
     * @param orderNum the value for payment_history.order_num
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_history.product_price
     *
     * @return the value of payment_history.product_price
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_history.product_price
     *
     * @param productPrice the value for payment_history.product_price
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setProductPrice(Integer productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_history.payment_type
     *
     * @return the value of payment_history.payment_type
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_history.payment_type
     *
     * @param paymentType the value for payment_history.payment_type
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setPaymentType(Integer paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_history.user_id
     *
     * @return the value of payment_history.user_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_history.user_id
     *
     * @param userId the value for payment_history.user_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_history.payment_time
     *
     * @return the value of payment_history.payment_time
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Date getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_history.payment_time
     *
     * @param paymentTime the value for payment_history.payment_time
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setPaymentTime(Date paymentTime) {
        this.paymentTime = paymentTime;
    }
}