package com.sybinal.shop.model;

import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.categoryid
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Integer categoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.discount
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Integer discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.shopprice
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Integer shopprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.quantity
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.hot
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Integer hot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productstatus
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Integer productstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.inventoryflag
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Integer inventoryflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.updatetime
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.updateuser_id
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Integer updateuserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.createtime
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.createuser_id
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Integer createuserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.categoryid
     *
     * @return the value of product.categoryid
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Integer getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.categoryid
     *
     * @param categoryid the value for product.categoryid
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setCategoryid(Integer categoryid) {
        this.categoryid = categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.discount
     *
     * @return the value of product.discount
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.discount
     *
     * @param discount the value for product.discount
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.shopprice
     *
     * @return the value of product.shopprice
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Integer getShopprice() {
        return shopprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.shopprice
     *
     * @param shopprice the value for product.shopprice
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setShopprice(Integer shopprice) {
        this.shopprice = shopprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.quantity
     *
     * @return the value of product.quantity
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.quantity
     *
     * @param quantity the value for product.quantity
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.hot
     *
     * @return the value of product.hot
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Integer getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.hot
     *
     * @param hot the value for product.hot
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setHot(Integer hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productstatus
     *
     * @return the value of product.productstatus
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Integer getProductstatus() {
        return productstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productstatus
     *
     * @param productstatus the value for product.productstatus
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setProductstatus(Integer productstatus) {
        this.productstatus = productstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.inventoryflag
     *
     * @return the value of product.inventoryflag
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Integer getInventoryflag() {
        return inventoryflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.inventoryflag
     *
     * @param inventoryflag the value for product.inventoryflag
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setInventoryflag(Integer inventoryflag) {
        this.inventoryflag = inventoryflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.updatetime
     *
     * @return the value of product.updatetime
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.updatetime
     *
     * @param updatetime the value for product.updatetime
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.updateuser_id
     *
     * @return the value of product.updateuser_id
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Integer getUpdateuserId() {
        return updateuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.updateuser_id
     *
     * @param updateuserId the value for product.updateuser_id
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setUpdateuserId(Integer updateuserId) {
        this.updateuserId = updateuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.createtime
     *
     * @return the value of product.createtime
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.createtime
     *
     * @param createtime the value for product.createtime
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.createuser_id
     *
     * @return the value of product.createuser_id
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Integer getCreateuserId() {
        return createuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.createuser_id
     *
     * @param createuserId the value for product.createuser_id
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setCreateuserId(Integer createuserId) {
        this.createuserId = createuserId;
    }
}