package com.sybinal.shop.model;

import java.util.Date;

public class Productcategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productcategory.id
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productcategory.sortorder
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Integer sortorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productcategory.updatetime
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productcategory.updateuserid
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Integer updateuserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productcategory.id
     *
     * @return the value of productcategory.id
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productcategory.id
     *
     * @param id the value for productcategory.id
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productcategory.sortorder
     *
     * @return the value of productcategory.sortorder
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Integer getSortorder() {
        return sortorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productcategory.sortorder
     *
     * @param sortorder the value for productcategory.sortorder
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setSortorder(Integer sortorder) {
        this.sortorder = sortorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productcategory.updatetime
     *
     * @return the value of productcategory.updatetime
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productcategory.updatetime
     *
     * @param updatetime the value for productcategory.updatetime
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productcategory.updateuserid
     *
     * @return the value of productcategory.updateuserid
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Integer getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productcategory.updateuserid
     *
     * @param updateuserid the value for productcategory.updateuserid
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setUpdateuserid(Integer updateuserid) {
        this.updateuserid = updateuserid;
    }
}