package com.sybinal.shop.model;

import java.util.Date;

public class ProductCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.name
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.sort_order
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.image
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.update_time
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.update_user_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.description
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.id
     *
     * @return the value of product_category.id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.id
     *
     * @param id the value for product_category.id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.name
     *
     * @return the value of product_category.name
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.name
     *
     * @param name the value for product_category.name
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.sort_order
     *
     * @return the value of product_category.sort_order
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.sort_order
     *
     * @param sortOrder the value for product_category.sort_order
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.image
     *
     * @return the value of product_category.image
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.image
     *
     * @param image the value for product_category.image
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.update_time
     *
     * @return the value of product_category.update_time
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.update_time
     *
     * @param updateTime the value for product_category.update_time
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.update_user_id
     *
     * @return the value of product_category.update_user_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.update_user_id
     *
     * @param updateUserId the value for product_category.update_user_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.description
     *
     * @return the value of product_category.description
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.description
     *
     * @param description the value for product_category.description
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setDescription(String description) {
        this.description = description;
    }
}