package com.sybinal.shop.model;

import java.util.Date;

public class Productimage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productimage.id
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productimage.productid
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Integer productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productimage.updatetime
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productimage.id
     *
     * @return the value of productimage.id
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productimage.id
     *
     * @param id the value for productimage.id
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productimage.productid
     *
     * @return the value of productimage.productid
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productimage.productid
     *
     * @param productid the value for productimage.productid
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productimage.updatetime
     *
     * @return the value of productimage.updatetime
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productimage.updatetime
     *
     * @param updatetime the value for productimage.updatetime
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}