package com.sybinal.shop.model;

public class ProductimageWithBLOBs extends Productimage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productimage.url
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private byte[] url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productimage.explain
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private String explain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productimage.url
     *
     * @return the value of productimage.url
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public byte[] getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productimage.url
     *
     * @param url the value for productimage.url
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setUrl(byte[] url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productimage.explain
     *
     * @return the value of productimage.explain
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public String getExplain() {
        return explain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productimage.explain
     *
     * @param explain the value for productimage.explain
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setExplain(String explain) {
        this.explain = explain;
    }
}