package com.sybinal.shop.model;

public class Sequence extends SequenceKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.no_counter
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer noCounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.no_counter
     *
     * @return the value of sequence.no_counter
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getNoCounter() {
        return noCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.no_counter
     *
     * @param noCounter the value for sequence.no_counter
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setNoCounter(Integer noCounter) {
        this.noCounter = noCounter;
    }
}