package com.sybinal.shop.model;

public class SequenceKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.type_code
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.counter_key
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String counterKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.type_code
     *
     * @return the value of sequence.type_code
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.type_code
     *
     * @param typeCode the value for sequence.type_code
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.counter_key
     *
     * @return the value of sequence.counter_key
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getCounterKey() {
        return counterKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.counter_key
     *
     * @param counterKey the value for sequence.counter_key
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setCounterKey(String counterKey) {
        this.counterKey = counterKey;
    }
}