package com.sybinal.shop.model;

public class Userroles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userroles.userroleid
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private Integer userroleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userroles.username
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private byte[] username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userroles.role
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private byte[] role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userroles.userroleid
     *
     * @return the value of userroles.userroleid
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public Integer getUserroleid() {
        return userroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userroles.userroleid
     *
     * @param userroleid the value for userroles.userroleid
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setUserroleid(Integer userroleid) {
        this.userroleid = userroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userroles.username
     *
     * @return the value of userroles.username
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public byte[] getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userroles.username
     *
     * @param username the value for userroles.username
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setUsername(byte[] username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userroles.role
     *
     * @return the value of userroles.role
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public byte[] getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userroles.role
     *
     * @param role the value for userroles.role
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setRole(byte[] role) {
        this.role = role;
    }
}