package com.sybinal.shop.model;

public class UsersWithBLOBs extends Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.nickname
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private byte[] nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private byte[] email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.openid
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private byte[] openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.oauthtype
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private byte[] oauthtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.image
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    private byte[] image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.nickname
     *
     * @return the value of users.nickname
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public byte[] getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.nickname
     *
     * @param nickname the value for users.nickname
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setNickname(byte[] nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public byte[] getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setEmail(byte[] email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.openid
     *
     * @return the value of users.openid
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public byte[] getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.openid
     *
     * @param openid the value for users.openid
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setOpenid(byte[] openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.oauthtype
     *
     * @return the value of users.oauthtype
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public byte[] getOauthtype() {
        return oauthtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.oauthtype
     *
     * @param oauthtype the value for users.oauthtype
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setOauthtype(byte[] oauthtype) {
        this.oauthtype = oauthtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.image
     *
     * @return the value of users.image
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public byte[] getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.image
     *
     * @param image the value for users.image
     *
     * @mbggenerated Thu Apr 15 21:45:38 CST 2021
     */
    public void setImage(byte[] image) {
        this.image = image;
    }
}