package com.sybinal.shop.model;

import java.util.Date;

public class Wishlist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wishlist.id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wishlist.product_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wishlist.option_value_ids
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private String optionValueIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wishlist.user_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wishlist.mark_time
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    private Date markTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wishlist.id
     *
     * @return the value of wishlist.id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wishlist.id
     *
     * @param id the value for wishlist.id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wishlist.product_id
     *
     * @return the value of wishlist.product_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wishlist.product_id
     *
     * @param productId the value for wishlist.product_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wishlist.option_value_ids
     *
     * @return the value of wishlist.option_value_ids
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public String getOptionValueIds() {
        return optionValueIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wishlist.option_value_ids
     *
     * @param optionValueIds the value for wishlist.option_value_ids
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setOptionValueIds(String optionValueIds) {
        this.optionValueIds = optionValueIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wishlist.user_id
     *
     * @return the value of wishlist.user_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wishlist.user_id
     *
     * @param userId the value for wishlist.user_id
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wishlist.mark_time
     *
     * @return the value of wishlist.mark_time
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public Date getMarkTime() {
        return markTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wishlist.mark_time
     *
     * @param markTime the value for wishlist.mark_time
     *
     * @mbggenerated Wed Apr 14 21:24:32 CST 2021
     */
    public void setMarkTime(Date markTime) {
        this.markTime = markTime;
    }
}